### ISSUE TITLE
Sync with upstream

### ISSUE THREAD

**Issue by shubham1172** [dapr/fortio#2]
Pull changes from upstream and sync with v1.24.0-dapr.

**Comment by shubham1172** [comment]
@skyao I have created this https://github.com/shubham1172/dapr-fortio/tree/v1.38.4-dapr, but I don't have access to push it to this repository. Any ideas?

**Comment by skyao** [comment]
I have created the branch of v1.38.4 which is based on v1.38.4 tag of fortio/fortio.

You can now merge from v1.24.0-dapr to this new branch.

**Comment by shubham1172** [comment]
Thanks @skyao, I raised #3.

**Comment by skyao** [comment]
Thank you for this upgrade!
